#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Allworx")]
	public partial class AllworxDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AllworxDataContext() : 
				base(global::TestClasses.Properties.Settings.Default.AllworxConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AllworxDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllworxDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllworxDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AllworxDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chargedcall> chargedcalls
		{
			get
			{
				return this.GetTable<chargedcall>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chargedcalls")]
	public partial class chargedcall
	{
		
		private System.DateTime _calldate;
		
		private System.DateTime _calltime;
		
		private string _calltype;
		
		private string _placedto;
		
		private string _placedfrom;
		
		private double _duration;
		
		private string _rate;
		
		private string _charge;
		
		private string _acctcode;
		
		public chargedcall()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calldate", DbType="DateTime NOT NULL")]
		public System.DateTime calldate
		{
			get
			{
				return this._calldate;
			}
			set
			{
				if ((this._calldate != value))
				{
					this._calldate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calltime", DbType="DateTime NOT NULL")]
		public System.DateTime calltime
		{
			get
			{
				return this._calltime;
			}
			set
			{
				if ((this._calltime != value))
				{
					this._calltime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calltype", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string calltype
		{
			get
			{
				return this._calltype;
			}
			set
			{
				if ((this._calltype != value))
				{
					this._calltype = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placedto", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string placedto
		{
			get
			{
				return this._placedto;
			}
			set
			{
				if ((this._placedto != value))
				{
					this._placedto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placedfrom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string placedfrom
		{
			get
			{
				return this._placedfrom;
			}
			set
			{
				if ((this._placedfrom != value))
				{
					this._placedfrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Float NOT NULL")]
		public double duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_charge", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string charge
		{
			get
			{
				return this._charge;
			}
			set
			{
				if ((this._charge != value))
				{
					this._charge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acctcode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string acctcode
		{
			get
			{
				return this._acctcode;
			}
			set
			{
				if ((this._acctcode != value))
				{
					this._acctcode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
